name: Tests
on: [push]

jobs:
  # Runtime Tests
  runtime-test:
    name: Runtime Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: DeLaGuardo/setup-clojure@13.4
        with: 1.12.4.1582

      - name: Build tests
        run: clojure -M:cljs-test:cljs-adv

      - name: Run tests
        run: |
          node target/test/tests-advanced.js | tee test-out.txt
          grep -qxF '0 failures, 0 errors.' test-out.txt
